//Category related action constants
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERR = 'GET_CATEGORIES_ERR';

// Related to posts
export const GET_ALL_POSTS_FOR_CATEGORY_ERR = "GET_ALL_FOR_CATEGORY_ERR";
export const GET_ALL_POSTS_FOR_CATEGORY_SUCCESS = "GET_ALL_FOR_CATEGORY_SUCCESS";
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_ERR = 'GET_ALL_POSTS_ERR';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_ERR = 'GET_POST_ERR';
export const CLEAR_FORM_POST = 'CLEAR_FORM_POST';
export const DELETE_POST = 'DELETE_POST';
export const VOTE_ON_POST = 'VOTE_ON_POST';
export const VOTE_ON_POST_FROM_DETAIL_PAGE = "VOTE_ON_POST_FROM_DETAIL_PAGE";
export const SORT_POSTS = 'SORT_POSTS';

// Related to comments
export const GET_ALL_FOR_POST_SUCCESS = "GET_ALL_FOR_POST_SUCCESS";
export const GET_ALL_FOR_POST_ERR = "GET_ALL_FOR_POST_ERR";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_ERR = "GET_COMMENT_ERR";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const VOTE_ON_COMMENT = "VOTE_ON_COMMENT";
export const SORT_COMMENTS = "SORT_COMMENTS";
export const CLEAR_FORM_COMMENT = "CLEAR_FORM_COMMENT";
